version: '3'
services:
    mongo:
        image: aashreys/mongo-auth:latest
        restart: always
        environment:
          - AUTH=yes
          - MONGODB_ADMIN_USER=root
          - MONGODB_ADMIN_PASS=mysecret
          - MONGODB_APPLICATION_DATABASE=challenge
          - MONGODB_APPLICATION_USER=user
          - MONGODB_APPLICATION_PASS=pass
        ports:
          - "27017:27017"

    challenge-nodejs:
        build: .
        restart: always
        ports:
            - "8080:8080"
        environment:
            PORT: 8080
            AUTHORIZATION: example
            LOG_LEVEL: verbose
            CONNECTIONSTRING: mongodb://user:pass@mongo/challenge
        links:
            - mongo

    challenge-nodejs-test:
        build:
            context: .
            dockerfile: ./Dockerfile.test
        restart: always
        ports:
            - "8080:8080"
        environment:
            PORT: 8080
            AUTHORIZATION: example
            LOG_LEVEL: verbose
            CONNECTIONSTRING: mongodb://user:pass@mongo/challenge
        links:
            - mongo