version: '3'
services:
    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example

    challenge-nodejs:
        build: .
        restart: always
        ports:
            - "8080:8080"
        environment:
            PORT: 8080
        links:
            - mongo
